### ISSUE TITLE
Error no log data was reveived, requesting permission change of "latest.log" to '666'

### ISSUE THREAD

**Issue by poyrazhancilar** [SuperPykkon/minecraft-server-web-console#4]
Error no log data was reveived, requesting permission change of "latest.log" to '666'

What is that?

**Comment by MoonBarc** [comment]
I believe that means that you need to run something like `chmod` to change the permissions of the latest.log file, so that the console can access the file.
so `cd` into the directory and run `chmod 666 latest.log`

I think that will work.
